# Header
menu:
  Facebook:
    url: https://facebook.com/jtwebman
    icon: facebook
  Twitter:
    url: https://twitter.com/jtwebman
    icon: twitter
  Instagram:
    url: https://instagram.com/jtwebman
    icon: instagram

# Title on top left of menu. Leave empty to use main blog title
menu_title:

# URL of the Home page image
index_cover: /img/bg-cover-bitcoin.jpg

# Default post title
default_post_title: Untitled

# Google Analytics Tracking ID
google_analytics:

# set your own favicon
favicon:

# Social Accounts
twitter_url: https://twitter.com/jtwebman
twitter_handle: jtwebman
facebook_url: https://facebook.com/jtwebman
github_url:
gitlab_url:
linkedin_url:
mailto:
